openapi: '3.0.3'

info:
  title: CSE186 Database Book Example
  version: 0.2.0

servers:
  - url: http://localhost:3010/api/v0

paths:
  /book:
    get:
      description: Returns an array of books
      parameters:
        - in: query
          name: author
          schema:
            type: string
          required: false
          description: Author's name, in part or full, case insensetive
      responses:
        200:
          description: Array of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'

    post:
      description: Creates a new book
      requestBody:
        description: Application to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        201:
          description: Application response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        400:
          description: Invalid ISBN
        409:
          description: Conflict. Requested ISBN in use.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'

  /book/{isbn}:
    get:
      description: Returns a single book
      parameters:
      - name: isbn
        in: path
        description: ISBN of the book
        required: true
        schema:
          $ref: '#/components/schemas/ISBN'
      responses:
        200:
          description: Book found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        400:
          description: Invalid ISBN
        404:
          description: Book not found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
                
components:
  schemas:
    UnexpectedError:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    ISBN:
      type: string
      pattern: '^(97(8|9))?\d{9}(\d|X)$'
        
    Book:
      type: object
      additionalProperties: false
      properties:
        isbn:
          $ref: '#/components/schemas/ISBN'
        title:
          type: string
        author:
          type: string
        publisher:
          type: string
      required:
        - title
        - author 
        - isbn 
        - publisher
